// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxybtcassgrwkfoligqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4eWJ0Y2Fzc2dyd2tmb2xpZ3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDA5NDUsImV4cCI6MjA2MTYxNjk0NX0.r4tzwlyCab3wAUIYCZ5CslA-vB1FmkLPVRpP4sDE66M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);